name: Release Workflow

on:
  push:
    branches:
      - main  # Sadece 'release' dalına push edildiğinde çalışır

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      # 1. Depoyu checkout et
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Versiyon numarasını tanımla (aynı versiyon tüm adımlarda kullanılacak)
      - name: Set Release Version
        run: echo "VERSION=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      # 3. Proje dosyalarını zip oluştur, exclude edilen dosyaları çıkar
      - name: Archive Project Files
        run: |
          zip -r "release_$VERSION.zip" . -x "*.git*" "node_modules/*" ".editorconfig"

      # 4. GitHub CLI yükle
      - name: Install GitHub CLI
        uses: actions/cli@latest

      # 5. Release oluştur ve zip dosyasını ekle
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v$VERSION" "release_$VERSION.zip" --title "Release $VERSION" --notes "Automated release generated by GitHub Actions"
