name: Release Workflow

on:
  push:
    branches:
      - release  # Sadece 'release' dalına push edildiğinde çalışır

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      # 1. Depoyu checkout et
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Proje dosyalarını zip oluştur, exclude edilen dosyaları çıkar
      - name: Archive Project Files
        run: |
          # Versiyon numarası belirleme
          VERSION=$(date +'%Y-%m-%d %H:%M:%S')  # Benzersiz bir versiyon numarası
          
          # Klasör ve dosyaları ziplerken exclude et
          zip -r "turuncuweb-wordpress-core.zip" . -x "*.git*" "node_modules/*" ".editorconfig"

      # 3. GitHub CLI yükle
      - name: Install GitHub CLI
        uses: actions/setup-node@v3

      # 4. Release oluştur
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(date +'%Y-%m-%d %H:%M:%S')
          gh release create "v$VERSION" "turuncuweb-wordpress-core.zip" --title "Release $VERSION" --notes "Automated release generated by GitHub Actions"
