name: Release Workflow

on:
  push:
    branches:
      - main  # Sadece 'release' dalına push edildiğinde çalışır

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      # 1. Depoyu checkout et
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Proje dosyalarını zip oluştur, exclude edilen dosyaları çıkar
      - name: Archive Project Files
        run: |
          # Versiyon numarası belirleme
          VERSION=$(date +'%Y%m%d%H%M%S')  # Benzersiz bir versiyon numarası
          
          # Klasör ve dosyaları ziplerken exclude et
          zip -r "release_$VERSION.zip" . -x "*.git*" "node_modules/*" ".editorconfig"

      # 3. ZIP dosyasını release olarak yükle
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: "v$VERSION"
          release_name: "Release $VERSION"
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      # 4. ZIP dosyasını release'e ekle
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./release_$VERSION.zip"
          asset_name: "release_$VERSION.zip"
          asset_content_type: application/zip